### ISSUE TITLE
zip does not unpack

### ISSUE THREAD

**Issue by spyrosmas** [wimbrts/VHD_XP_Setup#1]
either the password is wrong or release file is corrupted (virus ?)

**Comment by wimbrts** [comment]
password = bootwimb is correct and zip file does unpack.

It is required to switch Windows Defender off since otherwise unpack is refused due to false positive, but there is no virus !!

**Comment by spyrosmas** [comment]
It had 4 byte difference with the one I was trying to download earlier. OS_Info.exe and PS.exe was bad and they wasn't unzip and I don't have Windows Defender. Seems like hex edit the zip file by hand. Now it is OK. Thanks.
